//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingTask
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bank_DBEntities : DbContext
    {
        public Bank_DBEntities()
            : base("name=Bank_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BalanceMaster> BalanceMasters { get; set; }
        public DbSet<CreditHistory> CreditHistories { get; set; }
        public DbSet<CustomerMaster> CustomerMasters { get; set; }
        public DbSet<LinkUserToRole> LinkUserToRoles { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<TellerMaster> TellerMasters { get; set; }
        public DbSet<TransferHistory> TransferHistories { get; set; }
    }
}
