//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditHistory
    {
        public string CreditrBankAccountNo { get; set; }
        public string SourceBankAccountNo { get; set; }
        public string SourceIFSCNo { get; set; }
        public string SourceBankName { get; set; }
        public string SourceAccountHolderName { get; set; }
        public decimal CreditAmount { get; set; }
        public int ID { get; set; }
    }
}
