//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public string CustomerName { get; set; }
        public string CustomerType { get; set; }
        public string Gender { get; set; }
        public string CustomerUserName { get; set; }
        public string Password { get; set; }
        public bool IsEnabled { get; set; }
        public string CustomerBankName { get; set; }
        public string CustomerBankAccountNo { get; set; }
        public string CustomerIFSCNo { get; set; }
    }
}
