//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class TellerMaster
    {
        public int TellerCode { get; set; }
        public string TellerName { get; set; }
        public string Gender { get; set; }
        public string TellerUserName { get; set; }
        public string Password { get; set; }
        public bool IsEnabled { get; set; }
    }
}
