//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferHistory
    {
        public string CustomerBankAccountNo { get; set; }
        public string DestinationBankAccountNo { get; set; }
        public string DestinationIFSCNo { get; set; }
        public string DestinationBankName { get; set; }
        public string DestinationAccountHolderName { get; set; }
        public decimal MasterAmount { get; set; }
        public decimal TranferAmount { get; set; }
        public decimal BalanceAmount { get; set; }
        public int ID { get; set; }
    }
}
